---
abstract: 'very simple CRUD (create/read/update/delete)'
author:
  - 'David Precious <davidp@preshweb.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-SimpleCRUD
no_index:
  directory:
    - t
    - inc
requires:
  CGI::FormBuilder: 0
  Dancer: 1.3
  Dancer::Plugin::Database: 1
  HTML::Table::FromDatabase: 1.1
  Test::More: 0
resources:
  bugtracker: https://github.com/bigpresh/Dancer-Plugin-SimpleCRUD/issues
  homepage: https://github.com/bigpresh/Dancer-Plugin-SimpleCRUD/wiki/Quick-intro
  repository: https://github.com/bigpresh/Dancer-Plugin-SimpleCRUD
version: 0.50
