--- #YAML:1.0
name:               Dancer-Plugin-SimpleCRUD
version:            0.01
abstract:           very simple CRUD (create/read/update/delete)
author:
    - David Precious <davidp@preshweb.co.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI::FormBuilder:     0
    Dancer:               1.2
    Dancer::Plugin::Database:  0.08
    HTML::Table::FromDatabase:  0.07
    SQL::Abstract:        0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
